### ISSUE TITLE
Uninitialized constant ImportProductsJob::SuckerPunch (NameError)

### ISSUE THREAD

**Issue by yawar-ali** [2beDigital/solidus_import_products#3]
I am getting this error the stack trace is : 
```
gems/ruby-2.3.1@rails5.0/bundler/gems/solidus_import_products-0cda8be1e910/app/jobs/import_products_job.rb:2:in `<class:ImportProductsJob>': uninitialized constant ImportProductsJob::SuckerPunch (NameError)
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/solidus_import_products-0cda8be1e910/app/jobs/import_products_job.rb:1:in `<top (required)>'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.3/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.3/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:475:in `each'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:475:in `block in eager_load!'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:473:in `each'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:473:in `eager_load!'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/engine.rb:354:in `eager_load!'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/application/finisher.rb:59:in `each'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/initializable.rb:30:in `run'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/MuhammadYawarAli/work/TECH-CREATIX/pislow-production/config/environment.rb:5:in `<top (required)>'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /Users/MuhammadYawarAli/.rvm/gems/ruby-2.3.1@rails5.0/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/MuhammadYawarAli/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

Whenever I try to start server or run any spree or solidus generate command I am getting above error not able to track why I am getting this error.

Its started after updating to `gem 'solidus', '~> 2.2.1'`

I also tried a clean install but same error coming each time even on : `rails generate solidus_import_products:install`

**Comment by SergiCarrasco** [comment]
Hi sweetevil,
This gem uses suker punch as active job backend, you need to add sucker punch gem in your project.
We will add the dependency in the next release.
Thank you.
